In [3]:
print(ord("Y") % 15 + 1)

15


In [44]:
#Basic matrix multiplication sample

import numpy as np

p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
print("Matrix p :")
print(p)
print("Matrix q :")
print(q)
  
# computing product
result = np.dot(p, q)
  
print("The matrix multiplication is :")
print(result)

Matrix p :
[[1, 2], [2, 3], [4, 5]]
Matrix q :
[[4, 5, 1], [6, 7, 2]]
The matrix multiplication is :
[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [13]:
import numpy as np

Ap = np.random.randint(0, 10, size=(3, 3, 2))
q= np.random.randint(0, 10, size=(3, 2, 4))

def multiply_matrix(array_one,array_two):
    return np.dot(array_one, array_two)
  
print("The matrix multiplication is :")
print(multiply_matrix(p,q))

The matrix multiplication is :
[[[16 13 16 12]
  [10  3 11 23]
  [17  7 14 15]]

 [[27 22 28 19]
  [17  5 17 38]
  [27 12 25 25]]

 [[49 40 52 33]
  [31  9 29 68]
  [47 22 47 45]]]


In [36]:
import numpy as np

p = np.random.randint(0, 10, size=(3, 3, 3))
q= np.random.randint(0, 10, size=(3, 3, 3))

def multiply_matrix(array_one,array_two):
    return np.dot(array_one, array_two)

new_matrix = multiply_matrix(p,q)

def inverse_matrix(inverse_matrix):
    return np.linalg.inv(inverse_matrix)

print("The matrix multiplication is :")
print(new_matrix)

print("The inverse matrix is :")
print(inverse_matrix(new_matrix))


The matrix multiplication is :
[[[[ 60  74  77]
   [ 54  64  67]
   [ 87  61  60]]

  [[ 80 113 119]
   [ 90 104  99]
   [117 105 121]]

  [[ 55  60  65]
   [ 41  49  56]
   [ 78  49  35]]]


 [[[ 70 110  95]
   [ 84 102  95]
   [111  71 122]]

  [[ 30  53  39]
   [ 40  50  45]
   [ 51  25  63]]

  [[ 35  77  56]
   [ 63  77  63]
   [ 63  42 112]]]


 [[[ 50  72  96]
   [ 66  70  62]
   [ 66 104  94]]

  [[ 85 121 123]
   [ 95 111 106]
   [126 105 128]]

  [[ 55 103  89]
   [ 85 101  86]
   [ 90  75 140]]]]
The inverse matrix is :
[[[[-1.48081535e-01  1.54076739e-01  1.79856115e-02]
   [ 1.55215827e+00 -1.85791367e+00  8.27338129e-02]
   [-1.36330935e+00  1.66546763e+00 -9.35251799e-02]]

  [[-3.12656221e-02  1.68254467e-02  1.69825604e-02]
   [-9.89816177e-03  6.06030309e-02 -3.98497422e-02]
   [ 3.88213617e-02 -6.88586405e-02  2.64236642e-02]]

  [[-6.68181818e-01  7.04545455e-01  1.13636364e-01]
   [ 1.90454545e+00 -2.04220779e+00 -2.69480519e-01]
   [-1.17727273e+00  1.28896104e+00

In [39]:
import numpy as np

p = np.random.randint(0, 10, size=(3, 3, 3))
q = np.random.randint(0, 10, size=(3, 3, 3))
inverse = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])

def multiply_matrix(array_one, array_two):
    return np.dot(array_one, array_two)

def inverse_matrix(inverse_matrix):
    return np.linalg.inv(inverse_matrix)

def solve_matrix(p, q):
    return np.linalg.solve(p, q)

result1 = solve_matrix(p, q)
result2 = np.matmul(np.linalg.inv(p), q)

print("Result 1:\n", result1)
print("Result 2:\n", result2)

if np.allclose(result1, result2):
    print("The results are equal.")
else:
    print("The results are not equal.")


Result 1:
 [[[-1.4375     -0.625      -0.4375    ]
  [ 2.625       4.75        0.625     ]
  [-0.6875     -5.125       0.3125    ]]

 [[ 0.1         0.5625      0.05      ]
  [ 0.6         0.25       -0.2       ]
  [ 0.55       -0.03125     0.775     ]]

 [[ 0.62962963  0.31746032  0.18518519]
  [ 0.03703704  0.82539683 -0.51851852]
  [ 0.25925926 -0.22222222  0.37037037]]]
Result 2:
 [[[-1.4375     -0.625      -0.4375    ]
  [ 2.625       4.75        0.625     ]
  [-0.6875     -5.125       0.3125    ]]

 [[ 0.1         0.5625      0.05      ]
  [ 0.6         0.25       -0.2       ]
  [ 0.55       -0.03125     0.775     ]]

 [[ 0.62962963  0.31746032  0.18518519]
  [ 0.03703704  0.82539683 -0.51851852]
  [ 0.25925926 -0.22222222  0.37037037]]]
The results are equal.


In [43]:
#Task 15 (1, 3, 6, 8, 13, 15, 16, 18, 20)

import numpy as np

p = np.array([[1, 3, 6, 8], [13, 15, 16, 0], [18, 20, 2, 0],[2, 6, 2, 2]])
q = np.array([[5, 7, 3, 4], [3, 5, 7, 0], [3, 5, 7, 12], [2, 6, 2, 2]])

x = np.linalg.solve(p, q)

print("The solution matrix is:\n", x)


The solution matrix is:
 [[ 0.01216686 -0.98783314  0.19640788  0.72769409]
 [ 0.13383546  1.13383546  0.16048667  0.00463499]
 [ 0.05214368  0.05214368  0.12746234 -0.59559676]
 [ 0.53418308  0.53418308  0.19466976  0.85399768]]


In [68]:
import numpy as np

def task_1(n):
    arr = np.zeros((n, n), dtype=int)
    for i in range(n):
        arr[i, i] = i+1
    return arr

print(task_1(5))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [72]:
import numpy as np

def task_2(n):
    arr = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            if (i+j) % 2 == 0:
                arr[i, j] = 0
            else:
                arr[i, j] = 1
    return arr

print(task_2(10))

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [98]:
import numpy as np

def task_3(n, m, r, c):
    arr = np.ones((n, m), dtype=int)
    for i in range(n):
        if i %r== 0:
            arr[i, :] = 0
        arr[i, c - 1] = 0
    return arr

print(task_3(6,7,2,3))

[[0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0]
 [1 1 0 1 1 1 1]]


In [107]:
import numpy as np

def task_4(n, m):
    arr = np.zeros((m, n), dtype=int)
    arr[0] = np.arange(n)
    return arr

print(task_4(3,4))

[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [119]:
import numpy as np

def task_5(n):
    arr = np.zeros((n, n), dtype=int)
    arr[::2] = 1
    return arr

print(task_5(5))

[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [122]:
import numpy as np

def task_6():
    input_str = input("Enter numbers : ")
    values_str = input_str.strip().split()

    values = [int(x) for x in values_str]
    arr = np.array(values)

    # here i replace non-zero elements with -1
    arr[arr != 0] = -1

    return arr

print(task_6())

Enter numbers : 3 4 0 9 7 0 6 0 4 0 3
[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]


In [134]:
import numpy as np

def task_8():
    zeros=0
    Non_zeros=0
    input_str = input("Enter numbers : ")
    values_str = input_str.strip().split()

    values = [int(x) for x in values_str]
    arr = np.array(values)

    for i in arr:
        if i == 0:
            zeros+=1
        else:
            Non_zeros+=1
    print("Zeros : "+ str(zeros))
    print("Non_zeros : "+  str(Non_zeros))

task_8()

Enter numbers : 3 4 0 9 8 2 4 0 8 4 0
zeros : 3
Non_zeros : 8


In [135]:
import numpy as np

def task_9(n):
    arr = np.arange(n, -1, -1)
    print(arr)

task_9(10)

[10  9  8  7  6  5  4  3  2  1  0]


In [208]:
import numpy as np


def task_10(n,m):
    arr = np.random.rand(n, m)
    arr_min = np.min(arr)
    arr_max = np.max(arr)
    arr_mean = np.mean(arr)
    arr_std = np.std(arr)
    
    print("Minimum value:", round(arr_min, 3))
    print("Maximum value:", round(arr_max, 3))
    print("Mean:", round(arr_mean, 3))
    print("Standard deviation:", round(arr_std, 3))
    
task_10(4,5)

Minimum value: 0.023
Maximum value: 0.999
Mean: 0.513
Standard deviation: 0.24
4 5
minimum: 0.126
maksimum: 0.968
mean: 0.522
deviation: 0.265


In [212]:
import numpy as np


def task_11(n):
    arr = np.ones((n, n), dtype=int)
    
    arr[0,:] = 0
    arr[-1,:] = 0
    arr[:,0] = 0
    arr[:,-1] = 0
    
    return arr
    
task_11(12)
    

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [231]:
import numpy as np


def task_12(n):
    arr = np.ones((n, n))
    
    arr[0,:] = 0.
    arr[-1,:] = 0.
    arr[:,0] = 0.
    arr[:,-1] = 0.
    return arr
    
task_12(4)
    

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [235]:
import numpy as np


def task_13(n):
    arr = np.zeros((n, n), dtype=int)
    arr[::2, ::2] = 0
    arr[1::2, 1::2] = 0
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr
    
task_13(8)
    

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [242]:
import numpy as np


def task_14(n):
    tile = np.array([[0, 1], [1, 0]])
    arr = np.tile(tile, (n//2, n//2))
    if n % 2 != 0:
        arr = np.pad(arr, ((0, 1), (0, 1)), null, null)
    return arr
    
task_14(8)
    

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [246]:
import numpy as np


def task_15(n):
    arr = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            if j % 2 == 0:
                arr[i, j] = 0
            else:
                arr[i, j] = 1 if i % 2 == 0 else 0
    
    return arr
    
task_15(5)
    

array([[0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0]])

In [323]:
import numpy as np


def task_16(n):
    n = n+1
    half_n = float(n/2)
    multiple_n = float(3*n/4)
    vector = list(range(n))
    print(half_n)
    print(multiple_n)
    for i in range(n):
        if half_n < vector[i] < multiple_n:
            vector[i] = 0            
    return vector
    
print(task_16(10))
    

5.5
8.25
[0, 1, 2, 3, 4, 5, 0, 0, 0, 9, 10]


In [324]:
def task_17(n):
    vector = np.arange(n+1)
    for i in range(n+1):
        if vector[i] < n/2 or vector[i] > 3*n/4:
            vector[i] *= -1
    return vector
task_17(10)

array([  0,  -1,  -2,  -3,  -4,   5,   6,   7,  -8,  -9, -10])

In [334]:
import numpy as np

def task_18(n):
    vector = np.random.randint(0, 100, n)
    unique_elements = len(set(vector))
    print(f"In vector {vector} there are {unique_elements} unique numbers")

task_18(30)


In vector [26 92 27 54 17 42 83 27 52 44 54 71 83 64 57 28  9 44 71 17 16 18 42 34
 97 89 99  1 68 51] there are 23 unique numbers


In [356]:
import numpy as np

def task_19(n):
    vector = np.linspace(0.091, 0.909, n)
    rounded_vector = np.around(vector, 3)
    print(rounded_vector)

task_19(10)


[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


In [366]:
import numpy as np

def task_20(n):
    vector = np.random.rand(n)
    print(f"Initial vector {vector}")
    max_index = np.argmax(vector)
    vector[max_index] = 0
    print(f"Modified vector {vector}")

task_20(5)


Initial vector [0.69177442 0.26618159 0.57798633 0.63215074 0.50954235]
Modified vector [0.         0.26618159 0.57798633 0.63215074 0.50954235]


In [394]:
import numpy as np

def task_21(n,m):
    vector = np.random.randint(0, m+1, size=(n,n))
    print("Initial vector:")
    print(vector)
    max_val = np.max(vector)
    max_indices = np.argwhere(vector == max_val)
    for idx in max_indices:
        vector[idx[0], idx[1]] = -max_val
    print("Modified vector:")
    print(vector)

task_21(4,10)


Initial vector:
[[10  9  7  0]
 [ 2  0  6  2]
 [ 8  3 10  9]
 [ 0  2  2  4]]
Modified vector:
[[-10   9   7   0]
 [  2   0   6   2]
 [  8   3 -10   9]
 [  0   2   2   4]]
